Docker 1
Otus-DevOps-2018-11/mixassio_microservices pull request #1
Opened 2019-02-10 10:58 UTC by mixassio

2019-02-10 13:45 UTC, mrgreyves requested changes
Здравствуйте!) Вам нужно добавить описание к пуллреквесту

2019-02-11 12:07 UTC, mixassio commented
Добрый день! я его добавил в ветку `docker-1` но в пулл-реквест он не попал. Может он начнет попадать в пуллреквест когда окажется в мастере, то есть с второго пуллреквеста?
Проверил на предыдущем репозитории и там так же в первом PR шаблона не было

2019-02-11 12:09 UTC, mrgreyves commented
Ага, я вас понял=) Тогда нам стоит проверить это. Касательно дз, все хоршо =)

2019-02-11 12:10 UTC, mrgreyves approved these changes
UP!=)

2019-02-11 12:12 UTC, merged